### ISSUE TITLE
Timeout sending to remote device

### ISSUE THREAD

**Issue by CameronMease** [digidotcom/xbee-csharp#8]
On the Windows platform, calling ZigBeeDevice.SendData to send data to a remote XBee module, the call times out in AbstractXBeeDevice.SendXBeePacket().  See image:
![image](https://user-images.githubusercontent.com/2018275/88330048-d1adb780-ccf8-11ea-91d6-6966cdb55e55.png)

I verified that the remote device did receive the data.  Is this expected behavior?

**Comment by rubenmoral** [comment]
Hi @CameronMease,

I am not able to reproduce your issue on my side. The `TimeoutException` is thrown when the local module has not received a Transmit Status packet, which indicates the result of the transmission. For some reason, the library is not receiving that packet from the module, so it throws the exception.

What modules are you using? How large is the network?

**Comment by pgogte** [comment]
Hi I am facing the same problem. Interestingly I get this only for a broadcast. SendData to a known radio works but SendBroadcastData sometimes throws up TimeoutException.

2021-11-10 12:30:58.499 +03:00 [ERR] Could not transmit packet to 000000000000FFFF 18 bytes
XBeeLibrary.Core.Exceptions.TimeoutException: There was a timeout while executing the requested operation.
   at XBeeLibrary.Core.AbstractXBeeDevice.SendXBeePacket(XBeePacket packet)
   at XBeeLibrary.Core.AbstractXBeeDevice.SendAndCheckXBeePacket(XBeePacket packet, Boolean asyncTransmission)
   at XBeeLibrary.Core.AbstractXBeeDevice.SendData(XBee64BitAddress address, Byte[] data)
   at XBeeLibrary.Core.XBeeDevice.SendBroadcastData(Byte[] data)
